### ISSUE TITLE
Создать макет Окна чата при переписке

### ISSUE THREAD

**Issue by RSamokhin** [VanillaJs/chat#1]
- окно с историей сообщения 
- поле ввода
- список пользователей
- кнопка отправки сообшений

**Comment by anna-v** [comment]
Вопрос: а следуем ли мы moblile-first дизайну/вёрстке? Помню, это упоминалось 12-ого и все вроде бы были за, но так и не решили в итоге. Имхо, если мы будем поэтапно добавлять функционал, то работать на конкретном этапе удобнее на десктопной версии. Кто что думает?

**Comment by RSamokhin** [comment]
я за MF но, возможно стоит проголосовать :) + если нет охоты делать для мобилок, может и не стоит

**Comment by anna-v** [comment]
Для моб устройств делать определенно стоит, вопрос - в каком порядке? От мобильного к десктопу или наоборот.

**Comment by anna-v** [comment]
Так как у нас уже появился макет для десктопа, будем делать desktop first. :)
@neonov, выложи, пожалуйста.

**Comment by petersolopov** [comment]
![chat-main](https://cloud.githubusercontent.com/assets/10771967/9942571/76010fb0-5d84-11e5-9d80-3cec07b3338c.jpg)

**Comment by rndD** [comment]
:+1: :hotsprings:
