### ISSUE TITLE
Линтеры/хинтеры подготовить 

### ISSUE THREAD

**Issue by RSamokhin** [VanillaJs/chat#10]
Выбрать линтер
Подготовить конфиг / Найти!! конфиг
Повесить на хуки

**Comment by RSamokhin** [comment]
у нас на работе сейчас активно обсуждается переход на 
http://esfmt.org/ :) возможно, поможет

**Comment by effrenus** [comment]
У меня в саблайме установлен плагин ([SublimeLinter](https://github.com/roadhump/SublimeLinter-eslint)), который подсвечивает все несоответствия с код гайдом [airbnb](https://github.com/airbnb/javascript/tree/master/linters). Можно еще прекоммит худ добавить.

Примеры конфигов: [gist](https://gist.github.com/effrenus/eb551484e8432df73ca3); `.editorconfig` в корне, `.eslintrc`  в web

**Comment by emelyanovtv** [comment]
Я написал pre-commit и  хотел обсудить наш cs и тогда добавить .jshintrc c теми параметрами , которые нам нужны . Но я так понял , что это уже не актуально )
