### ISSUE TITLE
Настроить выполнение gulp тасков

### ISSUE THREAD

**Issue by effrenus** [VanillaJs/chat#16]
Хочется влиять на поведение тасков в ходе работы через параметры запуска (`gulp build --production|--develop`).
Т.е, если что-то разрабатываешь (develop mode), то не надо минифицировать цсс и джаваскрипт, есть создаешь для продакшн версию, то подключаем доп. модули. Как-то так=)

**Comment by RSamokhin** [comment]
Отличная идея :) можно по умолчанию сделать develop

**Comment by effrenus** [comment]
Таски настроил 0c79c930ce173de953315f00fc36ba7c94e9dec1. Для JS пока оставил `rigger`, но собираюсь поменять не `webpack`, в бранче реализующем функционал на `react`.

В readme напишу подробнее.
