### ISSUE TITLE
Работа с ветками

### ISSUE THREAD

**Issue by effrenus** [VanillaJs/chat#17]
Надо понять, как будем работать с ветками. Все ветки сливать с master не правильно, надо после  своей проверки мержить с `develop`, потом каждый вечер все проверяют `develop` и кто-то накатывает изменения в мастер и на сервер. Лучше это делать чаще, я так слышал.

_Вы как считаете?_

Насколько удобнее будет делать пулл-реквесты?

**Comment by anna-v** [comment]
Поддерживаю накатывание изменений в `master` через `develop`, но не уверена, будет ли у всех возможность проверять `develop` каждый день?

**Comment by RSamokhin** [comment]
Предлагаю всем работать со своими ветками, по максимуму часто обновляясь с девелоп, в ДЕВ мержим все вместе по пн-ср-сб, чекаем, что все ок и переносим в мастер

**Comment by dmikis** [comment]
А зачем вам отдельный `master` и `dev`? Почему не хватит одной? Больше сущностей – сложнее.

**Comment by effrenus** [comment]
Отказались от `develop` ветки, основная сейчас `master`, вливаем изменения через пулл реквесты.
Можно закрыть, кмк.
