### ISSUE TITLE
Скорректировать файловую систему web/src по БЭМ

### ISSUE THREAD

**Issue by anna-v** [VanillaJs/chat#19]
и перенастроить сборщик

**Comment by rndD** [comment]
Возможно вам хватит поменять под бэм только frontend.

**Comment by anna-v** [comment]
https://github.com/VanillaJs/chat/pull/22
Не разобралась до конца с js - как вписать имеющиеся сокет-скрипты в бэм? Спасите-помогите-подскажите, пожалуйста :)
