### ISSUE TITLE
Починить eslint

### ISSUE THREAD

**Issue by anna-v** [VanillaJs/chat#45]
Настроить eslint на игнорирование статики (картинки и шрифт)

**Comment by effrenus** [comment]
Поправил таск в package.json, должны проверяться только js, jsx файлы. Изменения в `master`, проверьте у себя, спс.

**Comment by anna-v** [comment]
Не совсем корректно работало. Поправила в отдельной ветке - см. [мой коммент](https://github.com/VanillaJs/chat/pull/51#issue-109283703) в пулл-реквесте.
