### ISSUE TITLE
Общая комната (lobby)

### ISSUE THREAD

**Issue by anna-v** [VanillaJs/chat#69]
1. Настроить вход в lobby по умолчанию
2. Добавить как отдельный канал в список

**Comment by emelyanovtv** [comment]
Нужно будет додумать как будет работать  общая комната

**Comment by anna-v** [comment]
UPD: Создать отдельный ID для лобби --> записывать историю сообщений, как и для всех других каналов

**Comment by anna-v** [comment]
Lobby теперь trolling room %)
