### ISSUE TITLE
#78 pr

### ISSUE THREAD

**Issue by emelyanovtv** [VanillaJs/chat#79]
#78

Проблема в том , что сообщения не делаются прочитанными , и отображение имени - хеш, а должно быть имя, остальное не тестил ((

**Comment by effrenus** [comment]
Вроде поправил.
Пока выводится последнее текстовое сообщение. Лучше показывать все, но в зависимости от типа делать разное оформление. Текст пока сокращается через substring, но т.к будет поддержка маркдауна, то надо что-то другое, например https://github.com/huang47/nodejs-html-truncate

**Comment by emelyanovtv** [comment]
Все ок
