### ISSUE TITLE
Доразбивать Gulp на модули

### ISSUE THREAD

**Issue by RSamokhin** [VanillaJs/chat#9]
p.s. не забыть таск билд - без вотчера для клиента

**Comment by effrenus** [comment]
Пётр в своей ветке разбил таски на файлы (см a647d972da80a176bb2a5eec9d80cd06c4c0b932); отдельный таск без вотчера уже есть: `build` в файле `gulp/tasks/groupTasks`. Создал `develop` ветку и смержил с `f-pn-001`. Там только надо поправить рут директорию для таска `webserver`, сделаю в своем бранче.

**Comment by RSamokhin** [comment]
ну ок - в пн замержим в мастер
